version: "3.9"

services:
  front:
    container_name: bingsu-project-front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
  
  back:
    container_name: bingsu-project-back
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
